# Generated by Django 4.2.10 on 2024-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='username')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('language', models.CharField(choices=[('uz', 'Uzbek')], default='uz', max_length=15)),
            ],
            options={
                'verbose_name': 'Telegram Profile',
                'verbose_name_plural': 'Telegram Profiles',
            },
        ),
    ]
